apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config-map
data:
  DATABASE_HOST: notification-db-service
  DATABASE_PORT: "27017"
  DATABASE_DATABASE: notifications
  DATABASE_USERNAME: mongo
  DATABASE_PASSWORD: password
  DATABASE_AUTH: admin
  RABBITMQ_HOST: rabbit-app-service
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: guest
  RABBITMQ_PASSWORD: guest
  SERVER_PORT: "8080"
  AUTH_SERVICE_URL: http://auth-app-service:8080/api/v1/auth
  ZIPKIN_URL: http://zipkin-app-service:9411/api/v2/spans