apiVersion: v1
kind: ConfigMap
metadata:
  name: tournament-config-map
data:
  DATABASE_URL: "jdbc:postgresql://tournament-db-service:5432/tournament"
  DATABASE_USERNAME: "postgres"
  DATABASE_PASSWORD: "postgres"
  AUTH_SERVICE_URL: http://auth-app-service:8080/api/v1/auth
  ZIPKIN_URL: "http://zipkin-app-service:9411/api/v2/spans"
  SERVER_PORT: "8080"